version: '3'
services:
  web:
    build: .
    container_name: server
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - "redis"
      - "db"
    ports:
      - "${HTTPS_SERVER_PORT}:443"
      - "${HTTP_SERVER_PORT}:80"
    volumes:
      - .AllTodo.Server:/code
      - logs:/var/log
    links:
      - redis
      - db
    networks:
      - todonet

  redis:
    image: redis
    networks:
      - todonet

  db:
    image: mysql
    networks:
      - todonet
    volumes:
      - datastore:/var/lib/mysql
    

volumes:
  logs:
  datastore:

networks:
  todonet:
